In [13]:
import numpy as np
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7],  ])
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [14]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [15]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp/4

2.0

In [16]:
a_cov = np.cov(a.transpose())
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [17]:
import pandas as pd

In [18]:
a = {'author_id' : [1, 2, 3],
           'author_name':['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(a)
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [19]:
b = {'author_id' : [1, 1, 1, 2, 2, 3, 3],
     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
     'price':[450, 300, 350, 500, 450, 370, 290]
}
books = pd.DataFrame(b)
print(books)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [20]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [21]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [7]:
c = { 
      "min_price": [],
      "max_price": [],
      "mean_price": []
}
author_stat = pd.DataFrame(c)
groupby = authors_price.groupby("author_name")
author_stat["min_price"] = groupby["price"].min()
author_stat["max_price"] = groupby["price"].max()
author_stat["mean_price"] = groupby["price"].mean()
print(author_stat)

             min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000


In [8]:

authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [12]:
book_info = pd.pivot_table(authors_price, index = "author_name", columns = "cover", values = "price", aggfunc = "sum", fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [31]:
book_info.to_csv('book_info.pkl', index = True)

In [32]:
book_info2 = pd.read_csv('book_info.pkl')
book_info2

author_name  мягкая  твердая
0  Островский     660        0
1    Тургенев     650      450
2       Чехов       0      950